from typing import Any, Protocol

class TenantBackendProtocol(Protocol):
    async def fetch_by_id(self, id: str) -> dict[str, Any] | None: ...
    async def fetch_by_slug(self, slug: str) -> dict[str, Any] | None: ...

class SystemFunctionBackendProtocol(Protocol):
    async def fetch(self, tenant_id: str) -> dict[str, Any] | None: ...

class TenantInfo:
    @property
    def id(self) -> str: ...
    @property
    def slug(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def active(self) -> bool: ...
    @property
    def settings(self) -> dict[str, Any]: ...
    def get_setting(self, key: str) -> str | None: ...
    def get_setting_i64(self, key: str) -> int | None: ...
    def get_setting_bool(self, key: str) -> bool | None: ...

class SystemFunctions:
    @property
    def tenant_id(self) -> str: ...
    @property
    def functions(self) -> dict[str, bool]: ...
    def is_active(self, function_name: str) -> bool: ...

class CacheConfig:
    def __init__(
        self,
        l1_max_capacity: int = 1000,
        l1_ttl_seconds: int = 300,
        l2_ttl_seconds: int = 900,
        enable_pubsub: bool = True,
    ) -> None: ...

class TenantCache:
    @classmethod
    async def create(
        cls,
        redis_url: str,
        backend: TenantBackendProtocol,
        config: CacheConfig,
    ) -> "TenantCache": ...
    async def get_by_id(self, id: str) -> TenantInfo | None: ...
    async def get_by_slug(self, slug: str) -> TenantInfo | None: ...
    async def is_tenant_active(self, id: str) -> bool: ...
    async def invalidate_by_id(self, id: str) -> None: ...
    async def invalidate_by_slug(self, slug: str) -> None: ...
    async def invalidate(self, id: str, slug: str) -> None: ...

class SystemFunctionCache:
    @classmethod
    async def create(
        cls,
        redis_url: str,
        backend: SystemFunctionBackendProtocol,
        config: CacheConfig,
    ) -> "SystemFunctionCache": ...
    async def get(self, tenant_id: str) -> SystemFunctions | None: ...
    async def invalidate(self, tenant_id: str) -> None: ...

def shutdown() -> None: ...
