name: OSV-Scanner
on:
  schedule:
    - cron: "0 7 * * 1"
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
        with:
          scan-args: |-
            -r
            ./
